config/routes.rb
Rails.application.routes.tap do |routes|
  app_config = Rails.configuration.vurse

  routes.default_url_options = {
    host:     app_config[:tld_host],
    protocol: app_config[:tld_protocol]
  }

  routes.draw do
    namespace :api do
      root to: 'root#index'
    end

    devise_for :users, skip: %i(confirmations invitations passwords registrations sessions unlocks)

    scope format: false do
      devise_scope :user do
        get '/accept-invitation' => 'invitations#edit', as: :accept_user_invitation
        get '/remove-invitation' => 'invitations#destroy', as: :remove_user_invitation
        post '/invitations' => 'invitations#create', as: :user_invitation
        get '/invitations/new' => 'invitations#new', as: :new_user_invitation
        patch '/invitations' => 'invitations#update', as: :update_user_invitation

        get '/login' => 'sessions#new', as: :new_user_session
        post '/login' => 'sessions#create', as: :user_session
        get '/logout' => 'sessions#destroy', as: :destroy_user_session

        get '/forgot-password' => 'passwords#new', as: :new_user_password
        post '/forgot-password' => 'passwords#create', as: :user_password
        get '/reset-password' => 'passwords#edit', as: :edit_user_password
        patch '/reset-password' => 'passwords#update', as: :update_user_password

        get '/unlock-account/resend' => 'unlocks#new', as: :new_user_unlock
        post '/unlock-account/resend' => 'unlocks#create', as: :user_unlock
        get '/unlock-account' => 'unlocks#show', as: :show_user_unlock

        get '/confirm-email/resend' => 'confirmations#new', as: :new_user_confirmation
        post '/confirm-email/resend' => 'confirmations#create', as: :user_confirmation
        get '/confirm-email' => 'confirmations#show', as: :show_user_confirmation

        if app_config[:registration_enabled].to_bool
          post '/register' => 'registrations#create', as: :user_registration
          get '/register' => 'registrations#new', as: :new_user_registration
        end

        get '/account' => 'registrations#edit', as: :edit_user_registration
        patch '/account' => 'registrations#update', as: :update_user_registration
        delete '/account' => 'registrations#destroy', as: :delete_user_registration
      end
    end

    get '/recent' => 'snippets#index', format: false

    root to: 'snippets#new', format: false

    resources :snippets, path: '/:username', only: %i(create show edit update destroy) do
      get '/raw' => 'raw_pieces#index', as: :raw
      get '/raw/:piece_id(/:name)' => 'raw_pieces#show', as: :raw_piece
    end

    get '/:username' => 'profiles#show', format: false, as: :profile
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include SnippetSortConcern

  before_action :authenticate_user!

  helper ApplicationHelper

  private

  def user
    @user ||= User.find_by!(username: params[:username])
  end
  helper_method :user

  def snippets
    @snippets ||= user.snippets
                  .order(current_sort_key => current_sort_direction)
                  .includes(:pieces)
                  .page(params[:page])
                  .per(10)
  end
  helper_method :snippets
end

app/views/profiles/show.html.erb
<article id="<%= user.id %>" class="container profile">
  <div class="col-lg-12">
    <header class="page-header">
      <h1><%= user == current_user ?  'Your Snippets' : user.username %></h1>
      <ul class="actions">
        <li>
          <div class="dropdown">
            <button id="snippets_sort_button" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort: <%= sort_label_for(current_sort_key, current_sort_direction) %>
              <%= icon('caret') %>
            </button>

            <ul class="dropdown-menu" role="menu" aria-labelledby="snippets_sort_button">
              <li><%= link_to sort_label_for(:created_at, :desc), profile_path(user.username) %></li>
              <li><%= link_to sort_label_for(:created_at, :asc), profile_path(user.username, sort: 'created_at:asc') %></li>
              <li><%= link_to sort_label_for(:updated_at, :desc), profile_path(user.username, sort: 'updated_at:desc') %></li>
              <li><%= link_to sort_label_for(:updated_at, :asc), profile_path(user.username, sort: 'updated_at:asc') %></li>
            </ul>
          </div>
        </li>
      </ul>
    </header>
  </div>
  <div class="col-lg-9">
    <%- unless snippets.empty? %>
      <%- snippets.each do |snippet| %>
        <article id="snippet_<%= snippet.id %>" class="panel panel-default snippet">
          <heading class="panel-heading">
            <h1 class="panel-title"><%= link_to user.username, profile_path(user.username) %> / <%= link_to render_sanitized(snippet.name), snippet_path(user.username, snippet.id) %></h1>
            <ul class="additional-info">
              <li><%= icon('file-code-o') %>&nbsp;<%= pluralize(snippet.pieces.size, 'piece') %></li>
            </ul>
          </heading>
          <div class="panel-body">
            <p><small><%= friendly_timestamp(snippet) %></small></p>
            <%- if snippet.description.present? %><p><small><%= render_markdown(snippet.description) %></small></p><% end -%>
            <pre><%= truncate(snippet.pieces.first.body, length: 256) %></pre>
          </div>
        </article>
      <% end -%>
      <%= paginate snippets %>
    <% else %>
      <p>Nothing here yet.</p>
    <% end -%>
  </div>
  <div class="col-lg-3">
    <div class="list-group snippet-filters">
      <%= link_to profile_path(user.username), class: ['list-group-item', (params[:filter].blank? ? 'active' : nil)].compact.join(' ') do %>
        <span class="badge"><%= current_user.snippets.size %></span>
        All snippets
      <% end %>
    </div>
  </div>
</article>