config/routes.rb
Rails.application.routes.tap do |routes|
  app_config = Rails.configuration.vurse

  routes.default_url_options = {
    host:     app_config[:tld_host],
    protocol: app_config[:tld_protocol]
  }

  routes.draw do
    namespace :api do
      root to: 'root#index'
    end

    devise_for :users, skip: %i(confirmations invitations passwords registrations sessions unlocks)

    scope format: false do
      devise_scope :user do
        get '/accept-invitation' => 'invitations#edit', as: :accept_user_invitation
        get '/remove-invitation' => 'invitations#destroy', as: :remove_user_invitation
        post '/invitations' => 'invitations#create', as: :user_invitation
        get '/invitations/new' => 'invitations#new', as: :new_user_invitation
        patch '/invitations' => 'invitations#update', as: :update_user_invitation

        get '/login' => 'sessions#new', as: :new_user_session
        post '/login' => 'sessions#create', as: :user_session
        get '/logout' => 'sessions#destroy', as: :destroy_user_session

        get '/forgot-password' => 'passwords#new', as: :new_user_password
        post '/forgot-password' => 'passwords#create', as: :user_password
        get '/reset-password' => 'passwords#edit', as: :edit_user_password
        patch '/reset-password' => 'passwords#update', as: :update_user_password

        get '/unlock-account/resend' => 'unlocks#new', as: :new_user_unlock
        post '/unlock-account/resend' => 'unlocks#create', as: :user_unlock
        get '/unlock-account' => 'unlocks#show', as: :show_user_unlock

        get '/confirm-email/resend' => 'confirmations#new', as: :new_user_confirmation
        post '/confirm-email/resend' => 'confirmations#create', as: :user_confirmation
        get '/confirm-email' => 'confirmations#show', as: :show_user_confirmation

        if app_config[:registration_enabled].to_bool
          post '/register' => 'registrations#create', as: :user_registration
          get '/register' => 'registrations#new', as: :new_user_registration
        end

        get '/account' => 'registrations#edit', as: :edit_user_registration
        patch '/account' => 'registrations#update', as: :update_user_registration
        delete '/account' => 'registrations#destroy', as: :delete_user_registration
      end
    end

    get '/recent' => 'snippets#index', format: false

    root to: 'snippets#new', format: false

    resources :snippets, path: '/:username', only: %i(create show edit update destroy) do
      get '/raw' => 'raw_pieces#index', as: :raw
      get '/raw/:piece_id(/:name)' => 'raw_pieces#show', as: :raw_piece
    end

    get '/:username' => 'profiles#show', format: false, as: :profile
  end
end

app/models/snippet.rb
# ## Schema Information
#
# Table name: `snippets`
#
# ### Columns
#
# Name               | Type               | Attributes
# ------------------ | ------------------ | ---------------------------
# **`created_at`**   | `datetime`         | `not null`
# **`description`**  | `text`             |
# **`id`**           | `uuid`             | `not null, primary key`
# **`name`**         | `string`           | `not null`
# **`owner_id`**     | `uuid`             | `not null, indexed`
# **`updated_at`**   | `datetime`         | `not null`
#
# ### Indexes
#
# * `snippets_ix_owner_id`:
#     * **`owner_id`**
#

class Snippet < ActiveRecord::Base
  DEFAULT_NAME_PREFIX = 'snippet'.freeze

  belongs_to :owner, class_name: 'User', required: true

  has_many :pieces, -> { order(:name) }, dependent: :destroy, inverse_of: :snippet

  accepts_nested_attributes_for :pieces, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true

  validate :validate_minimum_piece_count

  before_validation :set_defaults

  private

  def set_defaults
    persisted? ? identifier = id : identifier = SecureRandom.uuid
    suffix = identifier.gsub(/-/, '').to_i(16).to_s(36)
    self.name = [DEFAULT_NAME_PREFIX, suffix].join('-') if name.blank?
  end

  def validate_minimum_piece_count
    errors.add(:base, 'cannot remove the last piece') if pieces.size < 1 || all_pieces_marked_for_destruction?
  end

  def all_pieces_marked_for_destruction?
    pieces.all?(&:marked_for_destruction?)
  end
end

app/controllers/snippets_controller.rb
# Controller for CRUDing snippets.
class SnippetsController < ApplicationController
  include SnippetSortConcern

  before_action :authenticate_user!, except: %i(new)

  respond_to :html

  helper ApplicationHelper

  def index
    respond_with snippets
  end

  def new
    if user_signed_in?
      @snippet = Snippet.new
      @snippet.pieces.build
      render :new
    else
      # To avoid flash message
      redirect_to new_user_session_path
    end
  end

  def create
    create_snippet = CreateSnippet.call(user: current_user, params: snippet_params)
    if create_snippet.success?
      redirect_to snippet_path(current_user, create_snippet.snippet)
    else
      @snippet = create_snippet.snippet
      render :new
    end
  end

  def update
    update_snippet = UpdateSnippet.call(snippet: snippet, params: snippet_params)
    if update_snippet.success?
      redirect_to snippet_path(current_user, snippet)
    else
      @snippet = update_snippet.snippet
      render :edit
    end
  end

  def destroy
    snippet.destroy
    redirect_to profile_path(snippet.owner.username)
  end

  private

  def snippets
    @snippets ||= Snippet
                  .order(current_sort_key => current_sort_direction)
                  .includes(:pieces)
                  .page(params[:page])
                  .per(10)
  end
  helper_method :snippets

  def snippet
    @snippet ||= Snippet.includes(:pieces).find(params[:id])
  end
  helper_method :snippet

  def snippet_params
    params.require(:snippet).permit(:name, :description, pieces_attributes: %i(id name language body _destroy))
  end
end

app/views/snippets/_piece_fields.html.erb
<div class="panel panel-default nested-fields snippet-piece">
  <div class="panel-heading form-inline">
    <%= link_to_remove_association f, class: 'remove-snippet-piece' do %><%= icon('close') %>&nbsp;<span class="sr-only">Remove</span><% end %>
    <div class="form-group">
      <%= f.label :name, class: 'sr-only' %>
      <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
    </div>
  </div>
  <%= f.text_area :body, class: 'form-control editor-value' %>
  <div class="editor"></div>
</div>

app/views/snippets/_snippet_editor.html.erb
<%- content_for :stylesheets do %>
  <%= stylesheet_link_tag('vurse', media: 'all', 'data-turbolinks-track': true) %>
  <%= stylesheet_link_tag('vurse-editor', media: 'all', 'data-turbolinks-track': true) %>
<% end -%>
<%- content_for :javascripts do %>
  <%= javascript_include_tag('vurse', 'data-turbolinks-track': true) %>
  <%= javascript_include_tag('vurse-editor', 'data-turbolinks-track': true) %>
<% end -%>

app/views/snippets/_snippet_fields.html.erb
<div class="form-group">
  <%= f.label :name, class: 'sr-only' %>
  <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :description, class: 'sr-only' %>
  <%= f.text_area :description, placeholder: 'Description', class: 'form-control', rows: 3 %>
</div>

<div class="snippet-pieces">
  <%= f.fields_for :pieces do |piece| %>
    <%= render partial: 'snippets/piece_fields', locals: { f: piece } %>
  <% end %>
</div>

app/views/snippets/edit.html.erb
<%= render partial: 'snippets/snippet_editor' %>
<div class="container">
  <div class="col-lg-12">
    <header class="page-header">
      <h1>Editing <%= snippet.name %></h1>
    </header>
    <p><small><%= friendly_timestamp(snippet) %></small></p>
    <%= form_for snippet, url: snippet_path(snippet.owner.username, snippet), html: { method: :patch, class: 'snippet-form' } do |f| %>
      <%- snippet.errors.full_messages.each do |message| -%><p><%= message %></p><% end -%>

      <%= render partial: 'snippets/snippet_fields', locals: { f: f } %>

      <div class="form-group form-inline">
        <%= link_to_add_association 'Add file', f, :pieces, class: 'btn btn-default', 'data-association-insertion-node': '.snippet-pieces', 'data-association-insertion-method': 'append' %>
        <%= f.submit 'Update snippet', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/snippets/index.html.erb
<div id="all_snippets" class="container">
  <div class="col-lg-12">
    <header class="page-header">
      <h1>Recent Snippets</h1>
      <ul class="actions">
        <li>
          <div class="dropdown">
            <button id="snippets_sort_button" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort: <%= sort_label_for(current_sort_key, current_sort_direction) %>
              <%= icon('caret') %>
            </button>

            <ul class="dropdown-menu" role="menu" aria-labelledby="snippets_sort_button">
              <li><%= link_to sort_label_for(:created_at, :desc), recent_path %></li>
              <li><%= link_to sort_label_for(:created_at, :asc), recent_path(sort: 'created_at:asc') %></li>
              <li><%= link_to sort_label_for(:updated_at, :desc), recent_path(sort: 'updated_at:desc') %></li>
              <li><%= link_to sort_label_for(:updated_at, :asc), recent_path(sort: 'updated_at:asc') %></li>
            </ul>
          </div>
        </li>
      </ul>
    </header>
  </div>
  <div class="col-lg-9">
    <%- unless snippets.empty? %>
      <%- snippets.each do |snippet| %>
        <article id="snippet_<%= snippet.id %>" class="panel panel-default snippet">
          <heading class="panel-heading">
            <h1 class="panel-title"><%= link_to snippet.owner.username, profile_path(snippet.owner.username) %> / <%= link_to snippet.name, snippet_path(snippet.owner.username, snippet.id) %></h1>
            <ul class="additional-info">
              <li><%= icon('file-code-o') %>&nbsp;<%= pluralize(snippet.pieces.size, 'piece') %></li>
            </ul>
          </heading>
          <div class="panel-body">
            <p><small><%= friendly_timestamp(snippet) %></small></p>
            <pre><%= truncate(snippet.pieces.first.body, length: 256) %></pre>
          </div>
        </article>
      <% end -%>
      <%= paginate snippets %>
    <% else %>
    <% end -%>
  </div>
  <div class="col-lg-3">
    <div class="list-group snippet-filters">
      <%= link_to recent_path, class: ['list-group-item', (params[:filter].blank? ? 'active' : nil)].compact.join(' ') do %>
        All snippets
      <% end %>
    </div>
  </div>
</article>

app/views/snippets/show.html.erb
<article id="<%= snippet.id %>" class="container snippet">
  <div class="col-lg-12">
    <header class="page-header">
      <h1><%= link_to snippet.owner.username, profile_path(snippet.owner.username) %>&nbsp;/&nbsp;<%= link_to snippet_path(snippet.owner.username, snippet), title: "Permalink to #{snippet.name}" do %><%= snippet.name %>&nbsp;<%= icon 'link' %><% end %></h1>
      <ul class="actions">
        <li><%= link_to edit_snippet_path(snippet.owner.username, snippet), class: 'btn btn-default' do %><%= icon 'pencil' %>&nbsp;Edit<% end %></li>
        <li><%= link_to snippet_path(snippet.owner.username, snippet), class: 'btn btn-danger', 'data-method': :delete, 'data-confirm': 'Are you sure?' do %><%= icon 'trash' %>&nbsp;Delete<% end %></li>
      </ul>
    </header>
    <p><small><%= friendly_timestamp(snippet) %></small></p>
    <p><%= snippet.description %></p>
    <%- snippet.pieces.each do |piece| %>
      <section id="<%= piece.id %>" class="panel panel-default snippet-piece">
        <header class="panel-heading">
          <h1 class="panel-title"><%= link_to snippet_path(snippet.owner.username, snippet, anchor: piece.id), title: 'Permalink' do %><%= piece.name %>&nbsp;<%= icon 'link' %><% end %></h1>
          <ul class="actions">
            <li><%= link_to 'Raw', snippet_raw_piece_path(snippet.owner.username, snippet, piece, piece.name), class: 'btn btn-default btn-sm' %></li>
          </ul>
        </header>
        <div class="panel-body">
          <pre><%=raw piece.body %></pre>
        </div>
      </section>
    <% end -%>
  </div>
</article>