config/routes.rb
Rails.application.routes.tap do |routes|
  app_config = Rails.configuration.vurse

  routes.default_url_options = {
    host:     app_config[:tld_host],
    protocol: app_config[:tld_protocol]
  }

  routes.draw do
    namespace :api do
      root to: 'root#index'
    end

    devise_for :users, skip: %i(confirmations invitations passwords registrations sessions unlocks)

    scope format: false do
      devise_scope :user do
        get '/accept-invitation' => 'invitations#edit', as: :accept_user_invitation
        get '/remove-invitation' => 'invitations#destroy', as: :remove_user_invitation
        post '/invitations' => 'invitations#create', as: :user_invitation
        get '/invitations/new' => 'invitations#new', as: :new_user_invitation
        patch '/invitations' => 'invitations#update', as: :update_user_invitation

        get '/login' => 'sessions#new', as: :new_user_session
        post '/login' => 'sessions#create', as: :user_session
        get '/logout' => 'sessions#destroy', as: :destroy_user_session

        get '/forgot-password' => 'passwords#new', as: :new_user_password
        post '/forgot-password' => 'passwords#create', as: :user_password
        get '/reset-password' => 'passwords#edit', as: :edit_user_password
        patch '/reset-password' => 'passwords#update', as: :update_user_password

        get '/unlock-account/resend' => 'unlocks#new', as: :new_user_unlock
        post '/unlock-account/resend' => 'unlocks#create', as: :user_unlock
        get '/unlock-account' => 'unlocks#show', as: :show_user_unlock

        get '/confirm-email/resend' => 'confirmations#new', as: :new_user_confirmation
        post '/confirm-email/resend' => 'confirmations#create', as: :user_confirmation
        get '/confirm-email' => 'confirmations#show', as: :show_user_confirmation

        if app_config[:registration_enabled].to_bool
          post '/register' => 'registrations#create', as: :user_registration
          get '/register' => 'registrations#new', as: :new_user_registration
        end

        get '/account' => 'registrations#edit', as: :edit_user_registration
        patch '/account' => 'registrations#update', as: :update_user_registration
        delete '/account' => 'registrations#destroy', as: :delete_user_registration
      end
    end

    get '/recent' => 'snippets#index', format: false

    root to: 'snippets#new', format: false

    resources :snippets, path: '/:username', only: %i(create show edit update destroy) do
      get '/raw' => 'raw_pieces#index', as: :raw
      get '/raw/:piece_id(/:name)' => 'raw_pieces#show', as: :raw_piece
    end

    get '/:username' => 'profiles#show', format: false, as: :profile
  end
end

app/views/partials/_authentication_links.html.erb
<ul class="list-group">
<%- if controller_name != 'sessions' %>
  <li class="list-group-item"><%= link_to "Log in", new_user_session_path %></li>
<% end -%>
<%- if controller_name != 'passwords' %>
  <li class="list-group-item"><%= link_to "Forgot your password?", new_user_password_path %></li>
<% end -%>
<%- if controller_name != 'confirmations' %>
  <li class="list-group-item"><%= link_to "Need email confirmation instructions?", new_user_confirmation_path %></li>
<% end -%>
<%- if controller_name != 'unlocks' %>
  <li class="list-group-item"><%= link_to "Locked out of your account?", new_user_unlock_path %></li>
<% end -%>
</ul>

app/views/partials/_flash_messages.html.erb
<%- if flash.any? %>
  <div class="container">
    <div class="col-lg-12">
      <div class="flash">
        <%- flash.each do |type, message| %>
          <div class="alert alert-<%= type %>"><p><%= message %></p></div>
        <% end -%>
      </div>
    </div>
  </div>
<% end -%>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-center">Vurse v<%= Vurse::VERSION::STRING %><%= "@#{File.read(Rails.root.join('REVISION'))}" if File.exist?(Rails.root.join('REVISION')) %> &bull; &copy; 2015 Tony Burns</p>
  </div>
</footer>

app/views/partials/_primary_nav.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand' do %>Vurse<% end -%>
    </div>

    <ul class="nav navbar-nav navbar-left">
      <li class="<%= 'active' if controller_name == 'snippets' && action_name == 'index' %>"><%= link_to 'All Snippets', recent_path %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to current_user.username, profile_path(current_user.username), title: 'Your Profile' %></li>
      <li><%= link_to root_path, title: 'New Snippet' do %><%= icon('plus') %><span class="sr-only">&nbsp;&nbsp;New Snippet</span><% end %></li>
      <li><%= link_to edit_user_registration_path, title: 'Settings' do %><i class="fa fa-cogs"></i><span class="sr-only">&nbsp;&nbsp;Settings</span><% end -%></li>
      <li><%= link_to destroy_user_session_path, title: 'Log Out' do %><i class="fa fa-sign-out"></i>&nbsp;<span class="sr-only">Log out</span><% end -%></li>
    </ul>
  </div>
</nav>